#!/bin/bash
#sh experiments/VGG_RGB_UCF_seqvlad_with_redu_stage1.sh
#sh experiments/VGG_RGB_UCF_seqvlad_with_redu_stage2.sh

#sh fine_action/VGG_RGB_UCF_seqvlad_with_redu_stage1.sh
#sh fine_action/VGG_RGB_UCF_seqvlad_with_redu_stage2.sh
sh fine_action/VGG_RGB_UCF_seqvlad_with_redu_stage1.sh
#sh fine_action/VGG_RGB_UCF_seqvlad_with_redu_stage2.sh
#sh fine_action/VGG_RGB_UCF_seqvlad_with_redu_stage3.sh

sh fine_action/VGG_RGB_UCF_seqvlad_with_redu_eval.sh
